[package]
name = "webgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = "1.23.1"
env_logger = "0.11.8"
glam = { version = "0.30.5", features = ["bytemuck"] }
image = "0.25.6"
log = "0.4.27"
pollster = "0.4.0"
wgpu = "26.0.1"
winit = "0.30.11"
